services:
  db:
    image: postgres:17rc1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  postgres_data: